kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: worker
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: worker
      name: worker
    spec:
      containers:
        - name: worker
          image: demokuberegistry.azurecr.io/kubeevo:v1
          command: [ "./worker-start.sh" ]
