apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeevologdir
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: kubeevologdir
    readOnly: false
  claimRef:
    namespace: default
    name: kubeevologdir
